import type { Metadata } from "next";
import "./globals.css";
import { Satoshi } from "./ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body className="antialiased">
          <h1 className={Satoshi.className}> </h1>
          {children}
        </body>
      </html>
   
  );
}
